# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ODU4M2M1ZjQzMTJiY2Y4ZTYwMzFkZjRkYWEyZDhlYWFiODBkMjA4ODkxZDViOTEyOTI5M2RlODIwNzg4NDMwYTZiNTAyMzA5YmUzZDMxOGRkZTBjMDkyNzZhMjBhZTBkYjNiMzNhMmU5YTAzZGJjYWViNjFiMTM4MGNhNWI4YTQ=
